<h3> Author: Amira Bahaa Eldin Maher "Sec1" </h3>

<h1 style="color:Purple;"> Dataset Information and defintion </h1>
<h2 style="color:gray;">Diabetes patient records were obtained from kaggle, Diabetes mellitus is one of the most common human diseases worldwide and may cause several health-related complications.
It is responsible for considerable morbidity, mortality, and economic loss. 
A timely diagnosis and prediction of this disease could provide patients with an opportunity to take the appropriate preventive and treatment strategies. To improve the understanding of risk factors, we predict type 2 diabetes. The analysis finds five main predictors of type 2 diabetes: glucose, pregnancy, body mass index (BMI), diabetes pedigree function, and age. We further explore a classification tree to complement and validate our analysis. The six-fold classification tree indicates glucose, BMI, and age are important factors, while the ten-node tree implies glucose, BMI, pregnancy, diabetes pedigree function, and age as the significant predictors. </h2>

<h2 style="color:Purple;">diabetes file is an excel file that have:</h2>

<h3 style="color:gray;" >9columns and 768 rows </h3>
<h3 style="color:gray;">First column is : pragnencies records for diabetes (Frequency of pregnancy)</h3>
<h3 style="color:gray;">second column is : Glucose records (Concentration of plasma glucose (mg/dL)	)</h3>
<h3 style="color:gray;">third column is : Blood Pressure for diabetes (Diastolic blood pressure (mm Hg)) </h3>
<h3 style="color:gray;">fourth column is : skinThickness (Tricep skinfold thickness (mm))</h3>
<h3 style="color:gray;">Fifth column is :Insulin (Two-hour serum insulin (mu U/ml))</h3>
<h3 style="color:gray;">sixth column is : BMI (Body mass index (kg/m2)) </h3>
<h3 style="color:gray;">seventh column is : DiabetesPedigreeFunction A function that determines the risk of type 2 diabetes based on family history, the larger the function, the higher the risk of type 2 diabetes.</h3>
<h3 style="color:gray;">eightth column is : age </h3>
<h3 style="color:gray;">ninth column is : Outcome Whether the person is diagnosed with type 2 diabetes (1 = yes, 0 = no).</h3>

<p style="color:purple;"> in this data there is no nulls value </p>

<p>No null or String values are existed in this dataset.</p>






In [43]:

#BY : Amira Bahaa Eldin Maher 


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [44]:
#converting from csv to dataframe variable
dataset = pd.read_csv('Diabetes dataset.csv')
print(dataset.shape)
dataset

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [45]:
#converting from csv to dataframe variable 
#removing corrupted values
dataset = pd.read_csv('Diabetes dataset.csv', na_values='?')
print(dataset.shape)
dataset

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [46]:
#checking if there are null values
dataset.isnull()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [47]:
#checking if there are null values then replace it
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [48]:
#there is no null values so no need to drop rows or columns or replacing null values methods


In [49]:
#seperating the columns
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


In [50]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [51]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [52]:
#recognizing if any of the datatypes have object so we'll need to conert it
dataset.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

# no objects

<h1>Author by: Gehad Ehab Kamal 'Sec 2'<h1>

<p>- Machine learning algorithms perform better when numericl values are scaled to a standard range</p>
<p>- the most popular two techniques are normalization and standardization</p>
<p>- Standardization scales each input separately by subtracting the mean and dividing by the standard deviation</p>

In [53]:
#split the data into two groups, one for trainnig and one for testing.
#first, unpack the return of the 'train_test_split' function which is tuple to 4 variables 
#the test_size is 20% and the trainning_size is 80% (it can be 70% train and 30% test)
#the random_state factor must be the same number in the whole codde

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)

(614, 8)
(154, 8)


In [54]:
x_train

array([[  2.   ,  84.   ,   0.   , ...,   0.   ,   0.304,  21.   ],
       [  9.   , 112.   ,  82.   , ...,  28.2  ,   1.282,  50.   ],
       [  1.   , 139.   ,  46.   , ...,  28.7  ,   0.654,  22.   ],
       ...,
       [ 10.   , 101.   ,  86.   , ...,  45.6  ,   1.136,  38.   ],
       [  0.   , 141.   ,   0.   , ...,  42.4  ,   0.205,  29.   ],
       [  0.   , 125.   ,  96.   , ...,  22.5  ,   0.262,  21.   ]])

In [55]:
x_test

array([[  6.   ,  98.   ,  58.   , ...,  34.   ,   0.43 ,  43.   ],
       [  2.   , 112.   ,  75.   , ...,  35.7  ,   0.148,  21.   ],
       [  2.   , 108.   ,  64.   , ...,  30.8  ,   0.158,  21.   ],
       ...,
       [  8.   ,  95.   ,  72.   , ...,  36.8  ,   0.485,  57.   ],
       [  2.   , 146.   ,  70.   , ...,  28.   ,   0.337,  29.   ],
       [  8.   ,  74.   ,  70.   , ...,  35.3  ,   0.705,  39.   ]])

In [56]:
#scaling is reducing the large data values into smaller numbers that helps the algorithm to to get trained well and faster 
#instead of data set where the values of the features hava high differences with each other
#use the 'StandardScaler' library, to scale the x part in trainning set and testing set from column 0 to 6 
#that have large values from other columns that has 0, 1 values.

from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train[:,0:7]=sc.fit_transform(x_train[:,0:7])
x_test[:,0:7]=sc.transform(x_test[:,0:7])

In [57]:
x_train

array([[-0.52639686, -1.15139792, -3.75268255, ..., -4.13525578,
        -0.49073479, 21.        ],
       [ 1.58804586, -0.27664283,  0.68034485, ..., -0.48916881,
         2.41502991, 50.        ],
       [-0.82846011,  0.56687102, -1.2658623 , ..., -0.42452187,
         0.54916055, 22.        ],
       ...,
       [ 1.8901091 , -0.62029661,  0.89659009, ...,  1.76054443,
         1.981245  , 38.        ],
       [-1.13052335,  0.62935353, -3.75268255, ...,  1.34680407,
        -0.78487662, 29.        ],
       [-1.13052335,  0.12949347,  1.43720319, ..., -1.22614383,
        -0.61552223, 21.        ]])

In [58]:
x_test

array([[ 6.81856121e-01, -7.14020375e-01, -6.17126581e-01, ...,
         2.60735607e-01, -1.16372467e-01,  4.30000000e+01],
       [-5.26396861e-01, -2.76642826e-01,  3.01915686e-01, ...,
         4.80535176e-01, -9.54231000e-01,  2.10000000e+01],
       [-5.26396861e-01, -4.01607840e-01, -2.92758722e-01, ...,
        -1.53004759e-01, -9.24519704e-01,  2.10000000e+01],
       ...,
       [ 1.28598261e+00, -8.07744136e-01,  1.39731757e-01, ...,
         6.22758427e-01,  4.70396586e-02,  5.70000000e+01],
       [-5.26396861e-01,  7.85559793e-01,  3.16091372e-02, ...,
        -5.15027579e-01, -3.92687515e-01,  2.90000000e+01],
       [ 1.28598261e+00, -1.46381046e+00,  3.16091372e-02, ...,
         4.28817631e-01,  7.00688159e-01,  3.90000000e+01]])

<h1>Author by: Aya Yehia Khaled Hamouda 'Sec 1'</h1>

In [64]:
#BY : Aya Yehia Khaled Hamouda, sec 1
outliers=[]
def detect_outliers(dataset):
    
    threshold=3
    mean=np.mean(dataset)
    std=np.std(dataset)
    
    for i in dataset:
        z_score=(i- mean)/std
        if np.abs(z_score) > threshold:
            outliers.append(i)
    return outliers

In [63]:
outlier_pt=detect_outliers(dataset)

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

In [65]:
outlier_pt

NameError: name 'outlier_pt' is not defined